export default function AboutPage() {
    return (
      <div className="flex flex-col items-center justify-center min-h-screen p-8 space-y-8 w-full">
        {/* Title */}
        <h1 className="text-4xl font-bold text-center">About EquiLearn</h1>
        
        {/* Problem/Causes Section */}
        <section className="max-w-4xl text-left">
          <h2 className="text-2xl font-semibold">Contributing Factors to Educational Inequality</h2>
          <p className="mt-4 text-lg">
            Educational inequity stems from a variety of socioeconomic and systemic factors that greatly prevent children from accessing quality learning opportunities and resources. This is an issue that both developing and developed nations face. Barriers such as “inequalities that originate in sex, health and cultural identity (ethnic origin, language, religion)" prevent kids from accessing neccesary education, even though these are greatly decided during birth, and are uncontrollable (Right to Education). Financial constraints further exacerbate the issue, as many countries do not have the required resources to “create schools, provide schooling materials, nor recruit and train teachers" (Right to Education).  Education is a right, and a priority for all children, and when countries fail to allocate the resources for their future generations, the overall growth of a country can stall indefinitely. Additionally, inadequate teacher preparation and overcrowded classrooms create challenging learning environments for children, especially those of younger age. In many regions, a single classroom can sometimes have classes where “many different educational levels are forced together which does not allow each individual child to benefit from an education adapted to their needs and abilities” (Right to Education). A striking example can be seen in Tanzania, where only 3.5% of sixth-grade students have “sole use of a reading book” (Rueckert). Classrooms need to be accustomed to a certain demographic of students. This is why the grade system was developed, so kids of the same age could learn at similar paces. Materials would also fit the age requirements, but if classrooms are like a mixing pot of ages and languages, and resources are only available to a fraction of the class, then a large majority of students will not benefit from school. Once again, gender inequality also plays a significant role in limiting educational access. In some communities, girls are viewed as having less educational potential and value than boys and are “forced into marriage, or made to stay at home to look after siblings and work on household chores" (Rueckert). The situation worsens in conflict-affected areas, where more than 75 million children across 35 countries are in urgent need of educational support and structure. Of this large demographic, young girls are “90% more likely to be out of secondary school in conflict areas than elsewhere” (Rueckert). Ultimately, the lack of education perpetuates a cycle of poverty, which traps families across generations with limited resources and opportunities for social and economic advancement.
          </p>
        </section>
        
        {/* Effects on Future Section */}
        <section className="max-w-4xl text-left">
          <h2 className="text-2xl font-semibold">Long-Term Impacts of Educational Deprivation on Youth
          </h2>
          <p className="mt-4 text-lg">
          A lack of education has profound effects on individuals and last through a majority of their adulthood. This influences many aspects of life, beyond academic achievement as well. One major consequence that becomes apparent in adulthood is the restriction of career opportunities. Those with lower levels of education struggle a lot to get stable, well-paying jobs. Many people in the demographic get stuck in this loop of cycling through minimum-wage jobs, and in some areas, like California, it’s very hard to survive. Moving is not always an option, and it requires a lot of additional fees and connections. According to the Virginia Commonwealth University Center on Society and Health, individuals with limited education are more likely to be employed in career paths that offer "high-risk… with few benefits," whereas those who have access to more educational opportunities can get stable, high paying jobs that provide financial security and stability as well as healthcare (Why Education Matters to Health: Exploring the Causes). The effects of educational deprivation can also spill into long-term health concerns. Research from Helpful Professor notes that, generally people with lower education levels, frequently experience “poorer health outcomes” and a greater likelihood of living in poverty, partly due to reduced access to healthcare (Drew). This link between education and the overall stable state of the mind and body highlights the essential role of learning while young. Both sources demonstrate how educational attainment can not only dictate financial stability at times but also impact the overall well-being and state of mind of a person, furthering the idea that quality education is essential in both economic and personal health outcomes.

          </p>
        </section>
        
        {/* Gamification/Solutions Section */}
        <section className="max-w-4xl text-left">
          <h2 className="text-2xl font-semibold">Gamification as an Innovative Educational Strategy
          </h2>
          <p className="mt-4 text-lg">
          The definition of gamification is to integrate game-like elements into an activity to encourage of create more motivation. In the case of education, gamification can be used as a learning strategy to increase student engagement and improve educational outcomes. Gamification can include, but is not limited to, point systems, creating a character, leaderboard, interactive activities, etc. This can help make the learning process more immersive and enjoyable, and give kids an incentive to learn. According to Edvisors, implementing gamification into classrooms or websites allows students to actively participate in lessons, and pay more attention as “game-based learning can boost engagement by making subjects feel more interactive and rewarding” (Redlin). Kids learn in different ways, and not all have the motivation to learn in a classroom with a packet and a lesson plan. Many kids need extra motivation in order to learn, and gamification has proved to be the extra push for unmotivated kids. Beyond engagement, gamification has also been proven to improve knowledge retention and skill development. Axon Park highlights that educational environments that utilize a gamified strategy often see “higher student participation and better long-term retention of concepts” (Verma). This was proved by the study conducted among 365 students at the School of Electrical and Computer Engineering of the National Technical University of Athens, Greece. In the study, a web-based gamified application called Horses for Courses was used as the experiment, and the study results showed that 89.45% of the student's learning performance had improved compared to lecture-based education. The overall results showed that the performance of the student body increased by a staggering 34.75%. These results unanimously show that gamification is a much more dynamic way to make education more engaging and give students a much more interactive and rewarding educational experience.
	Educational inequality, long-term deprivation of education, and a lack of class engagement are all contributing factors to the global learning gap, leaving millions of underprivileged students without the resources or opportunities needed for a financially stable and healthy life. Without access to a structured, curriculum system in schools, many kids struggle with limited career opportunities and have to take up minimum-wage jobs or in some cases cheap labor. However, by integrating gamification into digital learning platforms, available for free, students can experience a more interactive, engaging, and structured educational experience. With the improved retention of information and motivation, underprivileged students around the world can escape the cycle of poverty and get their dream job. Digital learning accompanied by gamification has the potential to create a lasting, positive impact for students worldwide.

          </p>
        </section>

{/* Works Cited Section */}
<section className="max-w-4xl text-left mt-8">
        <h2 className="text-2xl font-semibold">Works Cited</h2>
        <ul className="mt-4 text-lg list-disc pl-6">
          <li>Drew, Chris. “Lack of Education: 11 Lifelong Effects (2019).” The Helpful Professor, 26 July 2019, <a href="https://helpfulprofessor.com/lack-of-education/" className="text-blue-500 underline">helpfulprofessor.com/lack-of-education/</a>.</li>
          <li>Humanium. “Right to Education : Situation around the World - Humanium.” Humanium, 2024, <a href="https://www.humanium.org/en/right-to-education/" className="text-blue-500 underline">www.humanium.org/en/right-to-education/</a>.</li>
          <li>Redlin, Penny. “The Power of Gamification in Education.” Edvisors, 8 Mar. 2024, <a href="https://www.edvisors.com/blog/gamification-of-education/" className="text-blue-500 underline">www.edvisors.com/blog/gamification-of-education/</a>.</li>
          <li>Rueckert, Phineas. “10 Barriers to Education That Children Living in Poverty Face.” Global Citizen, 13 Aug. 2019, <a href="https://www.globalcitizen.org/en/content/10-barriers-to-education-around-the-world-2/" className="text-blue-500 underline">www.globalcitizen.org/en/content/10-barriers-to-education-around-the-world-2/</a>.</li>
          <li>Verma, Nikita. “How Effective Is Gamification in Education? 10 Case Studies and Examples.” Axon Park, 19 Feb. 2023, <a href="https://axonpark.com/how-effective-is-gamification-in-education-10-case-studies-and-examples/" className="text-blue-500 underline">axonpark.com/how-effective-is-gamification-in-education-10-case-studies-and-examples/</a>.</li>
          <li>Virginia Commonwealth University. “Why Education Matters to Health: Exploring the Causes.” Societyhealth.vcu.edu, Center on Society and Health, 13 Feb. 2015, <a href="https://societyhealth.vcu.edu/work/the-projects/why-education-matters-to-health-exploring-the-causes.html#gsc.tab=0" className="text-blue-500 underline">societyhealth.vcu.edu/work/the-projects/why-education-matters-to-health-exploring-the-causes.html#gsc.tab=0</a>.</li>
        </ul>
      </section>

      </div>
    );
  }
  